### ISSUE TITLE
hashes and descriptions are reversed?

### ISSUE THREAD

**Issue by keith4** [trisulnsm/trisul-scripts#3]
In ja3fingerprint.json, the chunk at the bottom (that was taken from the original salesforce fingerprint list) has the "desc" and "ja3_hash" fields backwards for some reason.

**Comment by trisulnsm** [comment]
Hi, 

Thanks for the heads up. Fixed now. 

This was due to an error in the csv_toja3.rb file that did the conversion, that is fixed as well now.
